//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealsSet
    {
        public int Id { get; set; }
        public int IdAgent { get; set; }
        public int IdClient { get; set; }
        public int IdTypeOfGoods { get; set; }
    
        public virtual AgentsSet AgentsSet { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual TypeOfGoodsSet TypeOfGoodsSet { get; set; }
    }
}
